
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Yemekhane_Gecis_Sistemi.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class duyurular
    {

        public int id { get; set; }

        public Nullable<int> gonderen_id { get; set; }

        public Nullable<int> kart_tipi_id { get; set; }

        [Required(ErrorMessage = "Konu baþlýðýný boþ býrakmayýnýz...!")]

        public string konu { get; set; }

        [Required(ErrorMessage = "Mesaj alanýný boþ býrakmayýnýz...!")]

        public string mesaj { get; set; }

        public Nullable<System.DateTime> kayit_tarihi { get; set; }



        public virtual kullanicilar kullanicilar { get; set; }

    }

}
