
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Yemekhane_Gecis_Sistemi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class kart_bilgileri
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public kart_bilgileri()
    {

        this.gecis_loglari = new HashSet<gecis_loglari>();

    }


    public int ID { get; set; }

    public Nullable<int> kullanici_id { get; set; }

    public string kart_no { get; set; }

    public Nullable<int> kart_tipi_id { get; set; }

    public Nullable<int> durum { get; set; }

    public Nullable<System.DateTime> son_gecerlilik_tarihi { get; set; }

    public Nullable<System.DateTime> kayit_tarihi { get; set; }

    public Nullable<System.DateTime> guncelleme_tarihi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<gecis_loglari> gecis_loglari { get; set; }

    public virtual kart_tipleri kart_tipleri { get; set; }

    public virtual kart_durumlari kart_durumlari { get; set; }

    public virtual kullanicilar kullanicilar { get; set; }

}

}
