

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Yemekhane_Gecis_Sistemi.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class DB : DbContext
{
    public DB()
        : base("name=DB")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<birimler> birimler { get; set; }

    public virtual DbSet<gecis_loglari> gecis_loglari { get; set; }

    public virtual DbSet<islem_sonuc> islem_sonuc { get; set; }

    public virtual DbSet<islem_tipleri> islem_tipleri { get; set; }

    public virtual DbSet<kart_tipleri> kart_tipleri { get; set; }

    public virtual DbSet<ucretler> ucretler { get; set; }

    public virtual DbSet<unvanlar> unvanlar { get; set; }

    public virtual DbSet<sistem_log> sistem_log { get; set; }

    public virtual DbSet<view_kullanicilar> view_kullanicilar { get; set; }

    public virtual DbSet<view_sistem_log> view_sistem_log { get; set; }

    public virtual DbSet<view_gecis_loglari> view_gecis_loglari { get; set; }

    public virtual DbSet<duyurular> duyurular { get; set; }

    public virtual DbSet<yetkiler> yetkiler { get; set; }

    public virtual DbSet<kart_durumlari> kart_durumlari { get; set; }

    public virtual DbSet<kullanicilar> kullanicilar { get; set; }

    public virtual DbSet<kart_bilgileri> kart_bilgileri { get; set; }


    public virtual ObjectResult<SP_KISI_GECIS_RAPORU_Result> SP_KISI_GECIS_RAPORU(string baslangic_tarihi, string bitis_tarihi)
    {

        var baslangic_tarihiParameter = baslangic_tarihi != null ?
            new ObjectParameter("baslangic_tarihi", baslangic_tarihi) :
            new ObjectParameter("baslangic_tarihi", typeof(string));


        var bitis_tarihiParameter = bitis_tarihi != null ?
            new ObjectParameter("bitis_tarihi", bitis_tarihi) :
            new ObjectParameter("bitis_tarihi", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KISI_GECIS_RAPORU_Result>("SP_KISI_GECIS_RAPORU", baslangic_tarihiParameter, bitis_tarihiParameter);
    }

}

}

