//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemekhane_Gecis_Sistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<birimler> birimler { get; set; }
        public virtual DbSet<gecis_loglari> gecis_loglari { get; set; }
        public virtual DbSet<islem_sonuc> islem_sonuc { get; set; }
        public virtual DbSet<islem_tipleri> islem_tipleri { get; set; }
        public virtual DbSet<kart_bilgileri> kart_bilgileri { get; set; }
        public virtual DbSet<kart_tipleri> kart_tipleri { get; set; }
        public virtual DbSet<kullanicilar> kullanicilar { get; set; }
        public virtual DbSet<ucretler> ucretler { get; set; }
        public virtual DbSet<unvanlar> unvanlar { get; set; }
        public virtual DbSet<View_Kullanicilar1> View_Kullanicilar1 { get; set; }
        public virtual DbSet<View_gecis_loglari> View_gecis_loglari { get; set; }
        public virtual DbSet<sistem_log> sistem_log { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
