//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemekhane_Gecis_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_sistem_loglari
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string islem_adi { get; set; }
        public Nullable<System.DateTime> islem_tarihi { get; set; }
        public string mesaj { get; set; }
    }
}
